# Generated by Django 6.0 on 2026-07-02 04:18

import django.db.models.deletion
from django.db import migrations, models

class AddFieldIfNotExist(migrations.AddField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        field = model._meta.get_field(self.name)
        table_name = model._meta.db_table
        column_name = field.column
        
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT COUNT(*) FROM information_schema.COLUMNS "
                "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s",
                [table_name, column_name]
            )
            exists = cursor.fetchone()[0] > 0
            
        if not exists:
            super().database_forwards(app_label, schema_editor, from_state, to_state)

class CreateModelIfNotExist(migrations.CreateModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        table_name = model._meta.db_table
        
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT COUNT(*) FROM information_schema.TABLES "
                "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s",
                [table_name]
            )
            exists = cursor.fetchone()[0] > 0
            
        if not exists:
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        AddFieldIfNotExist(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Auto-generated Stock Keeping Unit', max_length=50, null=True, unique=True),
        ),
        AddFieldIfNotExist(
            model_name='sitesettings',
            name='enable_telegram_order_alert',
            field=models.BooleanField(default=False, help_text='Send alert to Telegram when a new order is placed'),
        ),
        AddFieldIfNotExist(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='Telegram Bot Token', max_length=255, null=True),
        ),
        AddFieldIfNotExist(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram Chat ID (e.g., your ID or group ID)', max_length=255, null=True),
        ),
        CreateModelIfNotExist(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, help_text='Auto-generated unique variation SKU', max_length=100, unique=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.size')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
