# Generated by Django 6.0 on 2026-06-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, help_text='Google Tag Manager ID e.g. GTM-XXXXXXX', max_length=50, null=True),
        ),
    ]
