server {
    listen 80;
    server_name localhost;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Frontend
    location / {
        # Detect social media crawlers
        if ($http_user_agent ~* "facebookexternalhit|twitterbot|whatsapp|telegrambot|discordbot|googlebot|bingbot") {
            set $is_crawler 1;
        }

        # Only proxy products and blog posts for now
        if ($uri ~* "^/(product|blog)/") {
            set $is_seo_path 1;
        }

        if ($is_crawler = 1) {
            rewrite ^/(.*)$ /api/seo-proxy/?path=/$1 break;
            proxy_pass http://backend:8000;
        }

        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # API and Admin Proxy
    location ~ ^/(api|admin|staff) {
        proxy_pass http://backend:8000;
    }

    # Django Media
    location /media/ {
        alias /app/backend/media/;
    }

    # Django Static
    location /django_static/ {
        alias /app/backend/staticfiles/;
    }
}
